name: Validate

on:
    push:
    pull_request:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

permissions:
    contents: read

jobs:
    validate-hacs:
        runs-on: "ubuntu-latest"
        steps:
            - name: checkout
              uses: "actions/checkout@v7"
            - name: HACS validation
              uses: "hacs/action@main"
              with:
                  category: "integration"
            - name: "Validate Hassfest"
              uses: "home-assistant/actions/hassfest@master"
